export const FILTER_OPTIONS = {
  SHOW_ALL: "SHOW ALL",
  MY_POLLS: "MY POLLS",
  MY_VOTES: "MY VOTES"
}

export const SORT_OPTIONS = {
  NEWEST: "NEWEST",
  OLDEST: "OLDEST",
  MOST_VOTED: "MOST VOTED",
  MOST_POPULAR: "MOST POPULAR",
  CLOSEST_VOTE: "CLOSEST VOTE"
}
