export const FETCH_USER = "FETCH_USER"
export const FETCH_POLLS = "FETCH_POLLS"
export const FETCH_DETAILS = "FETCH_DETAILS"
export const SUBMIT_POLL = "SUBMIT_POLL"
export const SUBMIT_OPTION = "SUBMIT_OPTION"
export const DELETE_POLL = "DELETE_POLL"
export const SET_VOTE = "SET_VOTE"

export const SET_FILTER = "SET_FILTER"
export const SET_SORT = "SET_SORT"
export const SET_SEARCH = "SET_SEARCH"
export const RESET_DETAILS = "RESET_DETAILS"
export const RESET_POLL_FORM = "RESET_POLL_FORM"
